// Copyright (c) Zefchain Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Internal module with code generated by [`wit-bindgen`](https://github.com/jvff/wit-bindgen).

#![allow(missing_docs)]

// Export the contract interface.
wit_bindgen::generate!({
    world: "contract",
});

pub use self::contract::{
    ApplicationCallOutcome, ApplicationId, BlockHeight, BytecodeId, CalleeContext, ChainId,
    ChannelName, CryptoHash, Destination, ExecutionOutcome, MessageContext, MessageId,
    OperationContext, OutgoingMessage, Owner, Resources, SessionCallOutcome, SessionId,
    SessionState,
};
pub use self::exports::linera::app::contract_entrypoints::*;
use super::{
    __contract_execute_message, __contract_execute_operation, __contract_finalize,
    __contract_initialize,
};

/// Implementation of the contract WIT entrypoints.
pub struct Contract;

impl contract::Contract for Contract {
    fn initialize(argument: Vec<u8>) -> Result<(), String> {
        unsafe { __contract_initialize(argument) }
    }

    fn execute_operation(operation: Vec<u8>) -> Result<Vec<u8>, String> {
        unsafe { __contract_execute_operation(operation) }
    }

    fn execute_message(message: Vec<u8>) -> Result<(), String> {
        unsafe { __contract_execute_message(message) }
    }

    fn finalize() -> Result<(), String> {
        unsafe { __contract_finalize() }
    }
}
